# This file automatically overrides docker-compose.yml for development
# Use: docker compose up (defaults to development)
# Use: docker compose -f docker-compose.yml up (production only)

services:
  app:
    build:
      context: .
      target: dev
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:password@db:5432/finetuned_photo_gen
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=dev-secret-key
    volumes:
      - .:/app
      - /app/node_modules

  db:
    environment:
      - POSTGRES_DB=finetuned_photo_gen
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

volumes:
  postgres_data_dev: 